version: '3'
name: dev-cp-organization-deps
services:
  mongodb:
    image: mongo:6.0
    container_name: dev-mongodb
    ports:
      - 27000:27017
    volumes:
      - lemongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DEV_MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DEV_MONGO_INITDB_ROOT_PASSWORD}
volumes:
  lemongo: