version: '3'
services:
  cp-organization:
    image: gabriel0simpleg/cp-organization:latest
    container_name: cp-organization
    environment:
      - CP_ORGANIZATION_SECRETS_MANAGER_ACCESS_TOKEN=${CP_ORGANIZATION_SECRETS_MANAGER_ACCESS_TOKEN}
      - CP_ORGANIZATION_AMQP_CONNECTION_SECRET=${CP_ORGANIZATION_AMQP_CONNECTION_SECRET}
      - CP_ORGANIZATION_MONGODB_CONNECTION_SECRET=${CP_ORGANIZATION_MONGODB_CONNECTION_SECRET}