version: '3'
services:
  cp-organization:
    image: gabriel0simpleg/cp-organization:latest
    container_name: cp-organization
    environment:
      - CP_ORGANIZATION_AMQP_CONNECTION_FILE=/etc/cp_organization_config/amqp_connection.json
      - CP_ORGANIZATION_MONGODB_CONNECTION_FILE=/etc/cp_organization_config/mongodb_connection.json
      - CP_ORGANIZATION_AMQP_API_FILE=/etc/cp_organization_config/amqp_api.json
      - CP_ORGANIZATION_OPENID_CONNECT_CONFIG_FILE=/etc/cp_organization_config/openid_connect_config.json
    volumes:
      - ./config:/etc/cp_organization_config