version: '3'
services:
  cp-organization:
    image: gabriel0simpleg/cp-organization:latest
    container_name: cp-organization
    ports:
      - 8000:80
      - 8443:443
    environment:
      - SECRETS_MANAGER_ACCESS_TOKEN=${SECRETS_MANAGER_ACCESS_TOKEN}
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
volumes:
  mongodb_data: